import test from 'node:test';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import type {AddressInfo} from 'node:net';import {chromium,expect} from '@playwright/test';import {createUiServer} from './fixtures/ui-server.ts';
import type {BrowserConfig,CallbackReview} from '../contract/browser.ts';
test('settings explicitly review callbacks without running work and preserve unavailable rows', {timeout:60000},async t=>{
 let config:BrowserConfig={targetUrl:'http://127.0.0.1:41000/',signInUrl:'',scope:'',requirements:'',maxSteps:60,journeyTimeoutSeconds:60,externalOrigins:['http://localhost:41000'],authEndpoints:[]};let review:CallbackReview={application:{applicationId:'web',origin:'http://127.0.0.1:41000'}};
 const requests:{path:string;input:{config?:BrowserConfig}}[]=[];
 const state=()=>({config,callbacks:review,cases:[],runs:[],specs:{},preparation:null,accounts:[],capabilities:{provider:'openrouter',modelConfigured:false,playwright:{browserInstalled:true}}});
 const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import BrowserTestingPanel from '/src/BrowserTestingPanel.tsx';import {TestWorkspaceContext} from '/src/lib/use-test-workspace.tsx';import {createTestWorkspace} from '/src/lib/test-workspace.ts';import {TooltipProvider} from '/src/components/ui/tooltip.tsx';import '/src/index.css';import '/src/workspace.css';const controller=async(path,input)=>{const r=await fetch('/build/__controller'+path,input===undefined?{}:{method:'POST',body:JSON.stringify(input)});return r.json();};const workspace=createTestWorkspace({controller,pollInterval:0});workspace.activate({path:'/acme/app',branch:'main'},{browserTests:{beta:await controller('/api/browser')}});createRoot(document.getElementById('root')).render(React.createElement(TestWorkspaceContext.Provider,{value:workspace},React.createElement(TooltipProvider,{},React.createElement(BrowserTestingPanel,{repoPath:'/acme/app',stageId:'beta'}))));`;
 const server=await createUiServer(t,{configFile:fileURLToPath(new URL('../vite.config.ts',import.meta.url)),logLevel:'error',server:{host:'127.0.0.1',port:0},plugins:[{name:'callback-ui',resolveId(id){if(id.endsWith('/__callback.tsx'))return '\0callback';},load(id){if(id==='\0callback')return entry;},configureServer(server){server.middlewares.use(async(req,res,next)=>{
 if(req.url?.includes('/__controller')){const path=req.url.split('/__controller')[1];if(req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;const input=JSON.parse(body);requests.push({path,input});if(path==='/api/browser/config')config=input.config;}res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state()));return;}
 if(req.url==='/build/__callback'){res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml('/__callback','<div id="root"></div><script type="module" src="/build/__callback.tsx"></script>'));return;}next();});}}]});await server.listen();
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage();const url=`http://127.0.0.1:${(server.httpServer!.address() as AddressInfo).port}/build/__callback`;await page.goto(url);
 const open=async()=>{await page.getByRole('button',{name:'Edit test settings',exact:true}).click();return page.getByRole('dialog',{name:'Test settings'});};let dialog=await open();
 await dialog.getByRole('button',{name:'Add callback',exact:true}).click();await expect(dialog.getByRole('combobox',{name:'Callback host 1',exact:true})).toHaveText('Choose host');
 await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByText('Choose a callback host.',{exact:true})).toBeVisible();assert.equal(requests.length,0);
 await dialog.getByRole('combobox',{name:'Callback host 1',exact:true}).click();await page.getByRole('option',{name:'localhost',exact:true}).click();await expect(dialog.getByText('http://localhost:41000',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).not.toBeVisible();assert.deepEqual(config.callbackBindings,[{applicationId:'web',hostname:'localhost'}]);assert.deepEqual(config.externalOrigins,['http://localhost:41000']);
 dialog=await open();await dialog.getByLabel('Target URL',{exact:true}).fill('http://127.0.0.1:41001/');await expect(dialog.getByRole('button',{name:'Add callback',exact:true})).toBeDisabled();await expect(dialog.getByRole('combobox',{name:'Callback host 1',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Remove callback 1',exact:true}).click();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).not.toBeVisible();assert.deepEqual(config.callbackBindings,[]);
 config={...config,targetUrl:'http://127.0.0.1:41000/',callbackBindings:[{applicationId:'web',hostname:'localhost'}]};review={application:null,error:'Choose a ready managed application for its callback bindings.'};await page.reload();dialog=await open();await expect(dialog.getByText(review.error!,{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Add callback',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Remove callback 1',exact:true}).click();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).not.toBeVisible();assert.deepEqual(config.callbackBindings,[]);
 review={application:{applicationId:'web',origin:'http://127.0.0.1:41000'}};config.externalOrigins=Array.from({length:9},(_,i)=>`https://site${i}.example.test`);config.callbackBindings=[{applicationId:'web',hostname:'127.0.0.1'}];await page.reload();dialog=await open();await expect(dialog.getByRole('button',{name:'Add callback',exact:true})).toBeDisabled();await expect(dialog.getByText('http://127.0.0.1:41000',{exact:true})).toBeVisible();assert.equal(requests.some(r=>/\/(generate|discover|verify|approve|run)$/.test(r.path)),false);
});
