// Stands in for `opencode run --agent playwright-test-generator` in tests: no network, no model. It reads the plan the
// controller wrote, records what it was given (never the key's value), and writes a spec as the mode says.
// Usage: node fake-opencode.ts <mode> <log.jsonl> <prompt>
import { spawn } from 'node:child_process';
import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';

// The project the controller wrote, as far as this stand-in reads it; the tests assert what it records.
type OpenCodeProject = {
  agent: Record<string, { mode: unknown; model: unknown; tools: Record<string, unknown> }>;
  mcp: Record<string, { command: string[]; environment?: Record<string, string> }>; permission: unknown; provider: unknown; small_model?: unknown;
};
type ToolResult = { content: { text?: string }[]; isError?: boolean };
type McpClient = { connect(transport: unknown): Promise<void>; callTool(call: object, schema: undefined, options: object): Promise<ToolResult>; close(): Promise<void> };

const [requestedMode, log, prompt, , requestedAgent = 'playwright-test-generator'] = process.argv.slice(2), env = process.env;
const mode = requestedMode.replace(/^trace-/, '');
const opencode = JSON.parse(readFileSync('opencode.json', 'utf8')) as OpenCodeProject, plan = readFileSync('specs/plan.md', 'utf8');
const agent = opencode.agent[requestedAgent], server = opencode.mcp['playwright-test'];
const configPath = server.command[server.command.indexOf('--config') + 1], config = (await import(pathToFileURL(configPath).href)).default as { projects: { testDir: string }[] };
const seedPath = join(config.projects[0].testDir, 'seed.spec.mjs');
const ids = [...plan.matchAll(/\(milestone id: ([^)]+)\)/g)].map(match => match[1]);
const signIn = plan.includes('journey.signIn()');
const target = prompt.match(/generator_write_test to `([^`]+)`/)![1];
const modes = Object.fromEntries([['config', configPath], ['seed', seedPath], ['case', env.PERPETUAL_CASE], ['opencode', 'opencode.json'], ['plan', 'specs/plan.md']].map(([name, file]) => [name, statSync(file!).mode & 0o777]));
const record = (extra: object) => appendFileSync(log, `${JSON.stringify({ mode, prompt, cwd: process.cwd(), workspaceMode: statSync('..').mode & 0o777, plan, seed: readFileSync(seedPath, 'utf8'), config, modes,
  agent: { name: requestedAgent, mode: agent.mode, model: agent.model, allTools: agent.tools['*'], bash: agent.tools.bash, tools: agent.tools }, permission: opencode.permission, provider: opencode.provider, smallModel: opencode.small_model, mcp: server.command, mcpEnvironment: server.environment,
  prompts: statSync('.opencode/prompts/playwright-test-generator.md').isFile(), instructions: readFileSync(`.opencode/prompts/${requestedAgent}.md`, 'utf8'), git: statSync('.git').isDirectory(),
  env: { key: Boolean(env.OPENROUTER_API_KEY), account: env.PERPETUAL_ACCOUNT_USERNAME || null, password: Boolean(env.PERPETUAL_ACCOUNT_PASSWORD), channel: env.PERPETUAL_EVENT_CHANNEL ?? null, caseFile: env.PERPETUAL_CASE, target: env.PERPETUAL_TARGET_URL,
    home: env.HOME, xdg: env.XDG_CONFIG_HOME ?? null, cache: env.XDG_CACHE_HOME, npm: env.npm_config_cache, claude: env.OPENCODE_DISABLE_CLAUDE_CODE },
  ...extra })}\n`);
const contract = plan.match(/```json\n([\s\S]*?)\n```/)?.[1] ?? '';
const runInput = contract.includes('{run}') ? '    await page.getByLabel("Name").fill(`Item ${journey.run}`);\n' : '';
const valid = () => `import { test } from 'perpetual';\n\n// spec: specs/plan.md\ntest('Generated by ${mode}', async ({ page, journey }) => {\n${ids.map((id, index) => `  await journey.milestone('${id}', async () => {\n${index === 0 && signIn ? '    await journey.signIn();\n' : ''}${index === 0 ? runInput : ''}    await page.getByRole('button', { name: 'Save' }).click();\n  });`).join('\n')}\n});\n`;
const invalid = () => valid().replace("click();\n  });", "click();\n    await expect(page.getByText('Saved')).toBeVisible();\n  });");
const write = (file: string, code: string) => { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, code); };
const repairing = prompt.startsWith('The test in');

// The pinned test MCP server, started as OpenCode starts it: its environment with the configured one on top, in the
// project. call() says whether a tool answered with an error; outputs holds every answer.
async function connect() {
  const require = createRequire(server.command.find(part => /[\\/]cli\.js$/.test(part))!), { Client, StdioClientTransport } = require('playwright-core/lib/utilsBundle') as {
    Client: new (info: { name: string; version: string }) => McpClient; StdioClientTransport: new (options: object) => unknown;
  };
  const client = new Client({ name: 'fake-opencode', version: '0' }), outputs: string[] = [];
  await client.connect(new StdioClientTransport({ command: server.command[0], args: server.command.slice(1), cwd: process.cwd(), env: { ...env, ...server.environment }, stderr: 'ignore' }));
  const call = async (name: string, args: object) => {
    const result = await client.callTool({ name, arguments: args }, undefined, { timeout: 90000 });
    outputs.push(result.content.map(part => part.text || '').join('\n'));
    return Boolean(result.isError);
  };
  return { client, call, outputs };
}

// Plays a prompt-injected model that names a file outside the workspace as the seed, by absolute path, by a relative
// path out of the project and with another project, then reads the generator's log. It is given the path, never the
// file's content, and records whether any tool answer held that content.
async function readHostFile() {
  const { client, call, outputs } = await connect(), host = `${log}.host`, content = `host-file-${process.pid}-${Date.now()}`;
  writeFileSync(host, `secret: ${content}\n`);
  const setups: boolean[] = [];
  for (const [project, seedFile] of [['seed', host], ['seed', relative(process.cwd(), host)], ['tests', 'seed.spec.mjs']]) setups.push(await call('generator_setup_page', { plan, project, seedFile }));
  const readLog = await call('generator_read_log', {});
  await client.close();
  return { setups, readLog, read: outputs.some(text => text.includes(content)) };
}

// Plays a prompt-injected model through the pinned test MCP server. Code written anywhere the seed's process loads or
// resolves files would record the secrets that process holds.
async function generate() {
  const { client, call, outputs } = await connect();
  const project = plan.match(/\*\*Seed project:\*\* `([^`]+)`/)?.[1];
  if (!project) throw new Error('The plan must identify the seed project.');
  const setup = () => call('generator_setup_page', { plan, project, seedFile: 'seed.spec.mjs' });
  const leak = `${log}.leak`;
  const evil = `import { writeFileSync } from 'node:fs';\nwriteFileSync(${JSON.stringify(leak)}, JSON.stringify({ key: process.env.OPENROUTER_API_KEY ?? null, password: process.env.PERPETUAL_ACCOUNT_PASSWORD ?? null }));\nexport default {};\nexport const test = () => {};\n`;
  const setups = [await setup()], refused: Record<string, boolean> = {}, written: Record<string, boolean> = {};
  for (const fileName of ['playwright.config.mjs', 'opencode.json', '.opencode/prompts/playwright-test-generator.md', '.opencode/prompts/perpetual-grammar-repair.md', 'specs/plan.md', 'node_modules/perpetual/index.mjs',
    '../run/playwright.config.mjs', '../run/seed/seed.spec.mjs', '../run/node_modules/perpetual/index.mjs', configPath]) refused[fileName] = await call('generator_write_test', { fileName, code: evil });
  // Inside tests a write succeeds, but nothing there is loaded or on the seed's import path.
  for (const [fileName, code] of [['tests/node_modules/perpetual/index.mjs', evil], ['tests/node_modules/perpetual/package.json', '{"name":"perpetual","type":"module","exports":"./index.mjs"}'],
    ['tests/package.json', '{"name":"perpetual","type":"module","exports":"./evil.mjs"}'], ['tests/evil.mjs', evil], ['tests/tsconfig.json', '{"compilerOptions":{"allowJs":true,"paths":{"perpetual":["./evil.mjs"]}}}']]) written[fileName] = await call('generator_write_test', { fileName, code });
  setups.push(await setup());
  const wrote = await call('generator_write_test', { fileName: target, code: valid() });
  await client.close();
  return { setups, refused, written, wrote, leaked: existsSync(leak), exposed: outputs.join('\n').includes(env.PERPETUAL_ACCOUNT_PASSWORD!) };
}

// OpenCode v1.18.32 --format json envelopes, emitted by a real local child at the harness boundary.
if (requestedMode.startsWith('trace-')) {
  console.log(JSON.stringify({type:'tool_use',timestamp:Date.now(),sessionID:'private-session',part:{id:'private-part',type:'tool',tool:'playwright-test_generator_setup_page',state:{status:'completed',input:{plan},output:`${env.OPENROUTER_API_KEY} ${env.PERPETUAL_ACCOUNT_USERNAME} ${env.PERPETUAL_ACCOUNT_PASSWORD}`,time:{start:Date.now(),end:Date.now()}}}}));
  console.log(JSON.stringify({type:'tool_use',timestamp:Date.now(),part:{type:'tool',tool:'playwright-test_browser_click',state:{status:mode==='fail'?'error':'completed',input:{element:'Private account Save'},output:'Private browser contents',error:'Private error'}}}));
  if (mode === 'missing') console.log(JSON.stringify({type:'tool_use',part:{type:'tool',tool:'playwright-test_browser_handle_dialog',state:{status:'error',error:'No dialog visible'}}}));
  if (mode !== 'hang' && !mode.startsWith('blocked')) console.log(JSON.stringify({type:'step_finish',timestamp:Date.now(),part:{type:'step-finish',reason:mode==='fail'?'error':'stop',cost:0.001,tokens:{input:11,output:12,reasoning:0,cache:{read:0,write:0}}}}));
}

if (mode === 'hang') {
  const child = spawn(process.execPath, ['-e', 'setInterval(() => {}, 1000)'], { stdio: 'ignore' });
  record({ pids: [process.pid, child.pid] });
  setInterval(() => {}, 1000);
} else if (mode === 'fail') {
  record({});
  process.stdout.write(`thinking with ${env.OPENROUTER_API_KEY}\n`);
  process.stderr.write(`Provider rejected key ${env.OPENROUTER_API_KEY} for ${env.PERPETUAL_ACCOUNT_PASSWORD}\n`);
  process.exit(3);
} else if (mode === 'seed') {
  record({ generation: await generate() });
} else if (mode === 'read-host') {
  record({ hostFile: await readHostFile() });
  write(target, valid());
} else if (mode === 'missing' || mode === 'blocked' || mode === 'blocked-outside-case') {
  record({});
  if (!requestedMode.startsWith('trace-')) process.stdout.write(`${repairing ? 'generator_write_test: No test runner found.' : 'generator_setup_page: The seed could not pause.'} Key ${env.OPENROUTER_API_KEY}; account ${env.PERPETUAL_ACCOUNT_PASSWORD}\n`);
} else {
  record({});
  if (!requestedMode.startsWith('trace-')) process.stdout.write(`Using ${env.OPENROUTER_API_KEY}\n`);
  if (mode === 'tamper') { chmodSync(env.PERPETUAL_CASE!, 0o644); writeFileSync(env.PERPETUAL_CASE!, '{}'); }
  write(mode === 'repair' && !repairing ? 'tests/rename-the-display-name.spec.ts' : target, mode === 'invalid' || mode === 'repair' && !repairing ? invalid() : valid());
}
if (requestedMode.startsWith('trace-') && mode.startsWith('blocked')) {
  console.log(JSON.stringify({type:'text',part:{type:'text',text:JSON.stringify({perpetual_blocker:{milestone:mode==='blocked-outside-case'?12:2,kind:'request-unobserved'}}),time:{start:Date.now(),end:Date.now()}}}));
  console.log(JSON.stringify({type:'step_finish',timestamp:Date.now(),part:{type:'step-finish',reason:'stop',cost:0.001,tokens:{input:11,output:12,reasoning:0,cache:{read:0,write:0}}}}));
}
